@url_dev=http://localhost:5000/v1/api

### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json

{
    "name": "Shop ban tum lum",
    "email": "shop9@gmail.com",
    "password": "1234567890"
}